
The Kenya High School had its beginnings in 1910 when a co-educational school called the Nairobi European School began in buildings designed for police Barracks. In 1931 the boys were separated from the girls. In 1935, the school was renamed The European Girls Secondary School and had its first Headmistress, Miss Kerby appointed. The buildings consisted partly of temporary wooden huts located on the compound of the present Nairobi Primary school, with whom the secondary school shared the present buildings. Staff housing was scattered in the vicinity of Protectorate Hill. In 1939, the school was renamed The Kenya High School.

In 1942, Miss Stott succeeded Miss Kerby. By this time, because of the existing overcrowding and lack of modern facilities, there was considerable demand for a new school. By 1944, the present site of about 100 acres on Kileleshwa Hill had been approved and sterling pound 150 had been voted in the 1945 budget as a token sum towards the laying out of the grounds. Eventually, the total cost of building and laying out of the grounds reached sterling pounds 700,000.
The present school began to take shape and in 1950, 100 boarders moved into two boarding blocks of the partially completed new school. The site at that time looked very different from today. The trees and flowering shrubs, which do so much enhance and beautify the grounds, remained to be planted; the chapel, the library, and the swimming pool were yet to be built.


The swimming pool was completed in December 1952, with the aid of a government loan. This loan was finally paid off at the end of 1967. The Chapel was dedicated in 1959 and the library opened in 1963. In 1963, Miss Stott retired and Miss Leeves took over.


Just prior to miss Stott’s retirement, the first African and Asian girls were admitted. The first African girl to be admitted in 1961 was Ann Mithamo During the four years of Miss Leevers’ headship, the inter-racial pattern of the school began to take shape. Before Miss Leevers left, she handed over to Miss Barnes. In 1967 plans had been made for the building of the Art Studio. Later in 1967, it was decided to extend the plan of the Art room to include a Music room and Music practice room. This block was completed early in 1969 when the Hon. D. T. Arap Moi officially opened on sports day. The school is still without an assembly which had to be omitted from an earlier building plan owing to lack of funds.


In 1974 the school was taken over by the government and it began to take more African pupils and teachers. The first African Headmistress was Mrs R. Kariuki. She took over from Miss Barnes in January 1977 and left in July of the same year after handing over the school to Mrs. M. W. Wanjohi on 22nd July 1977 to August 1999. After Mrs Wanjohi’s retirement in September 1999, Mrs Rosemary Saina took over from September 1999 to July 2015, She Handed over to the Deputy Mrs Lucy Mugendi who stayed upto December 31st 2015 who later handed over to Mrs Flora Mulatya who is the current Principal of the school.


There was school committee as early as 1932, whose members dedicated themselves to the well being of the school, in 1960, these duties were transferred to the board of governors. The school has had very able Heads of the board of governors e.g. Sir Phillip Mitchell (1960-1963), Mr. J. G. Francis(1963-1965) and it is particularly indebted to Mr Charles Njonjo who served the school for 10 years (1966-1976), Mr. Geoffrey  Kariithi (1977-1988), Dr. Eddah Gachukia (1984-1988) became the first lady chairperson of the board, Ms. Margaret W. Kenyatta(1989-1996), Mrs. Damaris Ayodo who served in the board from 1975 became chairperson (1996-1999), Mrs. Rebecca Masese took over from 1999 to 2015 When Mr. Philip Njuki took over to date